### ISSUE TITLE
java.lang.NoClassDefFoundError: org/webjars/WebJarExtractor$Cache

### ISSUE THREAD

**Issue by scalway** [sbt/sbt-less#133]
whenever I add newer (than 1.1.2) verion of sbt-less to my `plugins.sbt` 

```
//addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.2")
addSbtPlugin("com.github.sbt" % "sbt-less" % "2.0.1")
```

sbt crashes at startup with:
```
java.lang.NoClassDefFoundError: org/webjars/WebJarExtractor$Cache
```

OS: Linux Ubuntu
JVM: tested few 11 and 17 to be sure... no difference.

full log:
```
[debug] > Exec(reload, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(onFailure loadFailed, None, None)
[debug] > Exec(loadp, None, None)
[info] welcome to sbt 1.9.9 (Ubuntu Java 11.0.22)
[debug]             Load.defaultLoad until apply took 1.296864ms
[debug]                       Load.loadUnit: plugins took 21.083444ms
[debug]                       Load.loadUnit: defsScala took 0.005011ms
[debug] [Loading] Scanning directory /home/CENSORED/code/app-server/project
[debug]                         Load.loadUnit: mkEval took 0.207695ms
[debug] [Loading] Found non-root projects 
[debug] [Loading] Done in /home/CENSORED/code/app-server/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin)))
[debug] Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.MiniDependencyTreePlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.MiniDependencyTreePlugin))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.MiniDependencyTreePlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 1.404524 ms
[info] loading settings for project app-server-build from plugins.sbt ...
[debug]                           Load.resolveProject(app-server-build) took 1.467439ms
[debug]                         Load.loadTransitive: finalizeProject(Project(id app-server-build, base: /home/CENZORED/code/app-server/project, plugins: List(<none>))) took 3.237364ms
[debug] [Loading] Done in /home/SAME/code/app-server/project, returning: (app-server-build)
[debug]                       Load.loadUnit: loadedProjectsRaw took 62.240526ms
[debug]                       Load.loadUnit: cleanEvalClasses took 3.280206ms
[debug]                     Load.loadUnit(file:/home/OHNO/code/app-server/project/, ...) took 87.289881ms
[debug]                   Load.apply: load took 88.527329ms
[debug]                   Load.apply: resolveProjects took 0.135482ms
[debug]                   Load.apply: finalTransforms took 14.956919ms
[debug]                   Load.apply: config.delegates took 0.526638ms
[debug]                   Load.apply: Def.make(settings)... took 135.797621ms
[debug]                   Load.apply: structureIndex took 38.395802ms
[debug]                   Load.apply: mkStreams took 0.002936ms
[info] loading project definition from /home/SOMETHING/code/app-server/project
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[error] java.lang.NoClassDefFoundError: org/webjars/WebJarExtractor$Cache
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
[error] 	at scala.collection.TraversableLike.to(TraversableLike.scala:786)
[error] 	at scala.collection.TraversableLike.to$(TraversableLike.scala:783)
[error] 	at scala.collection.AbstractTraversable.to(Traversable.scala:108)
[error] 	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)
[error] 	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)
[error] 	at scala.collection.AbstractTraversable.toList(Traversable.scala:108)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:216)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:59)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1330)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1275)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1254)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1233)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:701)
[error] 	at sbt.internal.Load$.timed(Load.scala:1407)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:701)
[error] 	at sbt.internal.Load$.timed(Load.scala:1407)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:695)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:493)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:181)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:246)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:555)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:571)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:501)
[error] 	at sbt.internal.Load$.load(Load.scala:480)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
[error] 	at sbt.internal.Load$.timed(Load.scala:1407)
[error] 	at sbt.internal.Load$.apply(Load.scala:242)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:57)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:964)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:964)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:917)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:151)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
[error] 	at sbt.Command$.process(Command.scala:190)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:246)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:246)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:279)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:164)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:164)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:164)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:145)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:120)
[error] 	at sbt.io.Using.apply(Using.scala:28)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:113)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:67)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:43)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:225)
[error] 	at sbt.xMain$.$anonfun$run$11(Main.scala:135)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
[error] 	at sbt.xMain$.withStreams$1(Main.scala:88)
[error] 	at sbt.xMain$.run(Main.scala:123)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
[error] 	at sbt.xMain.run(Main.scala:47)
[error] 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:159)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:21)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[error] 	at xsbt.boot.Boot$.run(Boot.scala:73)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: org.webjars.WebJarExtractor$Cache
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
[error] 	at scala.collection.TraversableLike.to(TraversableLike.scala:786)
[error] 	at scala.collection.TraversableLike.to$(TraversableLike.scala:783)
[error] 	at scala.collection.AbstractTraversable.to(Traversable.scala:108)
[error] 	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)
[error] 	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)
[error] 	at scala.collection.AbstractTraversable.toList(Traversable.scala:108)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:216)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:59)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1330)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1275)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1254)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1233)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:701)
[error] 	at sbt.internal.Load$.timed(Load.scala:1407)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:701)
[error] 	at sbt.internal.Load$.timed(Load.scala:1407)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:695)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:493)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:181)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:246)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:555)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:571)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:501)
[error] 	at sbt.internal.Load$.load(Load.scala:480)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
[error] 	at sbt.internal.Load$.timed(Load.scala:1407)
[error] 	at sbt.internal.Load$.apply(Load.scala:242)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:57)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:964)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:964)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:917)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:151)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
[error] 	at sbt.Command$.process(Command.scala:190)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:246)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:246)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:279)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:164)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:164)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:164)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:145)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:120)
[error] 	at sbt.io.Using.apply(Using.scala:28)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:113)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:67)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:43)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:225)
[error] 	at sbt.xMain$.$anonfun$run$11(Main.scala:135)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
[error] 	at sbt.xMain$.withStreams$1(Main.scala:88)
[error] 	at sbt.xMain$.run(Main.scala:123)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
[error] 	at sbt.xMain.run(Main.scala:47)
[error] 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:149)
[error] 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:159)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:44)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:21)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[error] 	at xsbt.boot.Boot$.run(Boot.scala:73)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: org/webjars/WebJarExtractor$Cache
[error] Use 'last' for the full log.
[debug] > Exec(loadFailed, None, None)
```

**Comment by mkurz** [comment]
Which sbt version  are you using in `project/build.properties`. Please use sbt 1.9.9 (or maybe 1.7.2).

Also make sure you quit sbt and run `sbt clean` once before you try again.

If all of this does not work, please post the output of (with sbt 1.9.9 or 1.7.2 applied):
```
sbt
> reload plugins
sbt:project> dependencyTree
# Please post the output in a comment
```

**Comment by mkurz** [comment]
@scalway Did you solve the problem?

**Comment by mkurz** [comment]
So I checked, this error occurs when you have both sbt-web jars on your classpath:
- "com.github.sbt"          % "sbt-web"
- "com.typesafe.sbt"       % "sbt-web"

Did you use Play 2.8.x and tried to upgrade to sbt-less 2.0.1? Then you also have to upgrade to Play 2.9 or newer (because 2.8 will pull in the typesafe jar, and 2.9 switched to the github one).

Just make sure you have only one jar of the above two groupIds on the classpath (so also make sure you upgrade all your sbt-web plugins at once).

**Comment by jducoeur** [comment]
Just a brief note of thanks -- I'm clearing a bunch of tech debt and have been wrestling with the same error, and this gave me the necessary hint as to what was wrong.  (In my case, looks like an sbt-web conflict between sbt-rjs/digest/gzip vs sbt-web-scalajs.)
