### ISSUE TITLE
LESS compilation fails with exception

### ISSUE THREAD

**Issue by KarelCemus** [sbt/sbt-less#68]
SBT-LESS plugin works fine in my 3 Linux environments but fails at my colleague's computer. He uses:

- latest Windows 7, 64 bit
- `java -version` says Java 1.8.0_45
- `sbt --version` says 0.13.5
- sbt-less 1.1.0, Rhino version

There is [minimal project](https://github.com/KarelCemus/sbt-less-test) to reproduce the issue. It fails during LESS compilation. However, it works fine in all my 3 Linuxes so it might not be that easy to reproduce it.

Do you have any hunch what causes the issue?

The exception stack trace is here:

```
No source available, here is the exception stack trace:
->com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: TypeError: [object Object] is not a function, it is object. (D:\Git\idea\matahari\project\target\node-modules\webjars\less\lib\less\index.js#4) at D:\Git\idea\matahari\project\target\node-modules\webjars\less\lib\less\index.js:4 (anonymous)
 at D:\Git\idea\matahari\project\target\node-modules\webjars\less\lib\less-node\index.js:1 (anonymous)
 at module.js:456 (anonymous)
 at module.js:474 (anonymous)
 at module.js:356 (anonymous)
 at module.js:312 (anonymous)
 at module.js:364 (anonymous)
 at module.js:380 (require)
 at D:\Git\idea\matahari\project\target\node-modules\webjars\less\index.js:1 (anonymous)
 at module.js:456 (anonymous)
 at module.js:474 (anonymous)
 at module.js:356 (anonymous)
 at module.js:312 (anonymous)
 at module.js:364 (anonymous)
 at module.js:380 (require)
 at D:\Git\idea\matahari\project\target\less\sbt-less-1.1.0.jar:14 (anonymous)
 at D:\Git\idea\matahari\project\target\less\sbt-less-1.1.0.jar:3 (anonymous)
 at module.js:456 (anonymous)
 at module.js:474 (anonymous)
 at module.js:356 (anonymous)
 at module.js:312 (anonymous)
 at module.js:497 (anonymous)
 at trireme.js:142 (startup)
 at trireme.js:923 (anonymous)
     com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
     com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
     scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
     scala.util.Try$.apply(Try.scala:161)
     scala.util.Success.map(Try.scala:206)
     scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
     scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
     scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
     scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
     scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by KarelCemus** [comment]
Do you have any idea what may cause the issue? Why isn't the application running? Any workaround or something?

Thanks in advance.

**Comment by huntc** [comment]
Sorry - no idea at a glance...

**Comment by Enalmada** [comment]
I just upgraded sbt-less from 1.0.6 to 1.1.0 and got this error.  Going back to 1.0.6 fixes the problem.
Windows 8.1 64bit, Java 1.8.0_40, play 2.4.1, 

```
play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[JsTaskFailure:
 C:\Users\Adam\code\mentormyself\project\target\node-modules\webjars\less\lib\le
ss\index.js:13
        functions: require('./functions')(environment),
                                         ^
TypeError: object is not a function
    at module.exports (C:\Users\Adam\code\mentormyself\project\target\node-modul
es\webjars\less\lib\less\index.js:13:42)
    at Object.<anonymous> (C:\Users\Adam\code\mentormyself\project\target\node-m
odules\webjars\less\lib\less-node\index.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Adam\code\mentormyself\project\target\node-m
odules\webjars\less\index.js:1:80)
    at Module._compile (module.js:460:26)
]
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReloa
d.scala:51) ~[na:na]
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReloa
d.scala:44) ~[na:na]
        at scala.Option.map(Option.scala:145) ~[scala-library-2.11.6.jar:na]
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na
:na]
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]

        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
 ~[na:na]
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
 ~[na:na]
        at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-librar
y-2.11.6.jar:na]
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:17) ~[na:na]
        at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun
$apply$3$$anonfun$2.apply(PlayRun.scala:60) ~[na:na]
Caused by: com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: C:\Users\Adam\code\ment
ormyself\project\target\node-modules\webjars\less\lib\less\index.js:13
        functions: require('./functions')(environment),
                                         ^
```

**Comment by athasach** [comment]
I also have the exact same issue that @Enalmada has, but on Mac OS X 10.10.3, Java 1.8.0_45, Play 2.4.1.

**Comment by joeboyscout04** [comment]
Also having this issue, Mac OSX 10.10.3, Java 1.8, Play 2.3.8

**Comment by genachka** [comment]
Same issue on Linux (Ubuntu 15.04 64bit) with Java 1.8.0_45 and Play 2.3.8, scala 2.11.6, sbt 0.13.5. Reverting to 1.0.6 fixes the issue.

**Comment by loicknuchel** [comment]
Same as @genachka with versions 1.0.0 and 1.1.0, using 1.0.6 fixes the issue.

**Comment by naderghanbari** [comment]
Same issue here on Mac OS, Java 1.8.0_45, Play 2.3.9.

**Comment by jpsimonroy** [comment]
Had this same issue and was able to work around it by deleting project/target & project/project and rebuilding.

**Comment by dzagorovsky** [comment]
@jpsimonroy , thank you!
Deleting project/target & project/project helps me too.

**Comment by huntc** [comment]
@KarelCemus are you also able confirm that clearing the project/project project/target and target folders works for you?

**Comment by KarelCemus** [comment]
@huntc Yes, I can confirm it works.

@jpsimonroy  Thank you!

**Comment by genachka** [comment]
@jpsimonroy  thanks, that fixed it for me too!

**Comment by djx314** [comment]
Good job +1

**Comment by renexdev** [comment]
Thanks works for me too!

**Comment by reid-spencer** [comment]
This has bitten me too and the workaround (deleting project/project, project/target, target) has not worked for me. Going back to 1.0.6 does work. 

I was using sbt-less 1.1.1 on Mac OSX 10.11.2 with Java 1.8.0_45 and Play 2.4.6.

**Comment by llb4ll** [comment]
Same issue here: Ubuntu 15:10, openjdk version "1.8.0_66-internal", play 2.5.0

**Comment by nelsonblaha** [comment]
For the record: me too, MacOs 10.12.2

**Comment by nremond** [comment]
Running `find . -name "target" | xargs rm -fr` fixed it for me.

**Comment by ikamthania** [comment]
Deleting target indeed worked.

**Comment by meherbenahmed07** [comment]
install node and all is good
